### ISSUE TITLE
Scope home page to current user

### ISSUE THREAD

**Issue by sirjamesgray** [WeWriteApp/WeWrite#10]
Home page is currently at `/pages` and it's globally scoped to all pages 

It should be scoped to what the `user` has access to
- `Pages`
    - mine
    - shared with me
- `Groups`
    - mine 
    - joined 

Eventually we'll add: 
- `activity feed`

**Comment by jonatfoodgroup** [comment]
We would check check the current user and query only pages relevant to them (for now). As for shared, groups, that will be near future. 

I think a relevant opportunity with this would be "saving" or "bookmarking" pages that would make it a bit easier before sharing / invites / etc. 

Me personally, want to be able to save things / add to reading list / etc versus have to join groups and keep up with links

**Comment by sirjamesgray** [comment]
@jonatfoodgroup as for "bookmarking" or "saving" we'll get rid of the need for this by adding a `page menu` option which says "Add to page..." and you select a target page to add the current page to 

https://wewrite-app.notion.site/Add-current-page-to-1001a441bda74c79afb9ba57378b51ec?pvs=4
