### ISSUE TITLE
Ability to set a page to be "private"

### ISSUE THREAD

**Issue by sirjamesgray** [WeWriteApp/WeWrite#11]
User should be able to set a page to `Private` so it's not shown on their User page. 

- [ ] should show private in the all pages view
- [ ] should still show up as a page for the user who created it
- [ ] If a user visits the page and is not the owner, a request access form should exist

**Comment by jonatfoodgroup** [comment]
It would show up on their user pages, but not on other users, correct?

**Comment by sirjamesgray** [comment]
@jonatfoodgroup if I set a page to private, it's visible for me, but it's not visible to you when you visit my `user page` (something that will come in the future)

**Comment by jonatfoodgroup** [comment]
@sirjamesgray regarding request access — this would be invites / queuing for invites. We will want to work on the sprint plan for the week for which feature needs to be implemented.
