### ISSUE TITLE
Changing a title results in loss of body content 

### ISSUE THREAD

**Issue by sirjamesgray** [WeWriteApp/WeWrite#21]
in this video I tried to reproduce the error but clicking the edit button caused what appears to me to be a different error. 

https://github.com/user-attachments/assets/ab698090-eb03-47c6-8162-688b1f66e34b

**Comment by jonatfoodgroup** [comment]
As part of the versions work, we will stop editing the main object of the content which will fix all of this. Overwrites have been occurring and versions will solve.

**Comment by sirjamesgray** [comment]
will be resolved with #24
