### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by jonatfoodgroup** [WeWriteApp/WeWrite#24]
- [x] Should be able to save a version of a page for historical reference. Should include timestamp, content, and who saved the version
- [x] Should have a currentVersion flag on the page itself that is used for the front end
- [ ] Versions should be deletable
- [x] When a user creates the page, that should be saved as the first version and set as the currentVersion for the page
- [x] When a user wants to delete a page, it should also delete all versionns
- [x] This should be saved as subcollection on the main pages/{id} collection object

**Comment by sirjamesgray** [comment]
I don't think versions should be deletable (they can on the data side but not for users)

**Comment by sirjamesgray** [comment]
"delete" should just deleted the whole page, the whole collection of all versions
