### ISSUE TITLE
Deleting Pages

### ISSUE THREAD

**Issue by jonatfoodgroup** [WeWriteApp/WeWrite#25]
The primary complication with deleting pages is when displaying links to deleted pages, we have to verify if that page is active. One opportunity for this is to get all links in the content of a page, get the ID of the pages in an array, and then check in the database which are active or inactive or deleted. 

- [x] Should check if a page has been removed from the database
- [x] Should check if a page is marked as private 
- [x] Should check all links in the content page at time of review

Another opportunity would be adding a collection of "deletedPages" that we could check for IDs on which would relate to less database calls but I don't think this is scalable.

**Comment by sirjamesgray** [comment]
@jonatfoodgroup can we mark this as done? or is it blocked by #11 ?

**Comment by jonatfoodgroup** [comment]
I believe this is complete @sirjamesgray
