### ISSUE TITLE
Initial search functionality 

### ISSUE THREAD

**Issue by sirjamesgray** [WeWriteApp/WeWrite#27]
triggered by the keyboard shortcut `cmd+k` 

this will reduce the risk of creating duplicate pages 

this will also be used for the `insert page dropdown` #35

**Comment by jonatfoodgroup** [comment]
So the initial page dropdown functionality would exist in this and then are we hoping to allow a user to search ALL pages on first version — meaning by any user to navigate to? Currently we do not have this. Only search for the current user’s page in a “scoped search” versus a global search for everything (users, groups, pages) etc.

**Comment by sirjamesgray** [comment]
but we could mark this as done and create a new task since "initial search" is done, and we could slot it for later
