### ISSUE TITLE
Delete functionality doesn't work 

### ISSUE THREAD

**Issue by sirjamesgray** [WeWriteApp/WeWrite#3]
Clicking the "delete" button doesn't do anything. 

It should not only delete the page, but all times it's linked in other pages, it should be replaced by a chip that says "deleted page" 

![CleanShot 2024-08-04 at 17 02 50@2x](https://github.com/user-attachments/assets/9360a094-7869-40c6-a727-3d138570ab4d)

**Comment by jonatfoodgroup** [comment]
The note on this is that we have to check ALL other pages content to see if the deleted page exists and then do the class reference -- I'm challenged on this one but will use GPT to help me make sense of it shortly.
