### ISSUE TITLE
Editing title disappears page

### ISSUE THREAD

**Issue by sirjamesgray** [WeWriteApp/WeWrite#5]
Editing a title makes the page disappear from the main list view on `/pages` as well as in the `Insert Page Dropdown` component which is triggered by the @ command

**Comment by sirjamesgray** [comment]
just discovered this is why the "WeWrite" page went missing @jonatfoodgroup

**Comment by jonatfoodgroup** [comment]
Bug was that when starting to edit, the current state of the editor was not saved for saving so it would save null in the db. This is fixed with the update of adding the current value into the editor. For whatever reason the title isn't liking to update at all.
