### ISSUE TITLE
Prevent pinch to zoom on PWA

### ISSUE THREAD

**Issue by sirjamesgray** [WeWriteApp/WeWrite#51]
eventually the pinch to zoom gesture will actually increase/decrease the UI size. If we could do that now, that'd be sick. but if not let's just block the pinch gesture entirely.

**Comment by jonatfoodgroup** [comment]
Commit has been added for this -- will go up on next release

**Comment by sirjamesgray** [comment]
@jonatfoodgroup did the release get pushed? 

on PWA on iOS it still supports pinch to zoom
