### ISSUE TITLE
prevent pill link clipping

### ISSUE THREAD

**Issue by sirjamesgray** [WeWriteApp/WeWrite#53]
![Image](https://github.com/user-attachments/assets/521197ff-c73e-417e-aa15-a28beb4d9246)

before clipping occurs, we should wrap the pill to the next row. upper limit would be that a pill can occupy a whole rendered line all by itself, at which point it should truncate within the pill (with "..." at the right side) and the full title can be viewed upon clicking (which takes you to the page)

**Comment by jonatfoodgroup** [comment]
This should be completed as of latest push. Please confirm 
@sirjamesgray

**Comment by sirjamesgray** [comment]
yep looks good to me ✅
