### ISSUE TITLE
Ability to delete group

### ISSUE THREAD

**Issue by sirjamesgray** [WeWriteApp/WeWrite#63]

**Comment by jonatfoodgroup** [comment]
To achieve this we need to update the groups on all the members with a cloud function and also all pages that are currently associated with a group need to have the reference removed .

**Comment by jonatfoodgroup** [comment]
<img width="1111" alt="image" src="https://github.com/user-attachments/assets/b06c8352-dad7-4aaa-b596-f38aff75594d">

**Comment by jonatfoodgroup** [comment]
Okay this is being pushed up now.
