### ISSUE TITLE
Add username field to registration flow

### ISSUE THREAD

**Issue by sirjamesgray** [WeWriteApp/WeWrite#70]
Should be able to set username during registration. I think this could also impact styling of login / auth pages.

**Comment by jonatfoodgroup** [comment]
This includes adding the hotfix in the flow for users that were created without username in the field on most recent PRs

**Comment by jonatfoodgroup** [comment]
This needs to be implemented better for the logic tree and styling.

**Comment by jonatfoodgroup** [comment]
@sirjamesgray Would love designs for this / where in the flow.
